<?php

return [
    'stepsLimit' => 4,
    'Column_Names' => [
        '1' => [
            'title' => 'General',
            'items' => [
                'AirCraft' => [
                    'AIRCRAFTREGISTRATION_NUMBER' => 'Registration',
                    'AIRCRAFTVARIANT_CAPTION' => 'Aircraft',
                    'MANUFACTUREDATE' => 'DOM',
                    'AIRCRAFT_OWNER' => 'Aircraft Owner',
                    'LEASESTART' => 'Lease Start',
                    'LEASEEND' => 'Lease End',
                ],
                'Engines' => [
                    'MODEL_CAPTION' => 'Engine Model',
                    'ESN1_ID' => 'ESN1',
                    'ESN2_ID' => 'ESN2',
                    'ESN3_ID' => 'ESN3',
                    'ESN4_ID' => 'ESN4',
                ],
                'APU' => [
                    'APU_SN' => 'APU SN',
                    'Model' => 'APU Model',
                ],
                'Landing Gears' => [
                    'NOSE_LDG_SN' => 'NOSE LDG SN',
                    'MAIN_LDG_LH1_SN' => 'MAIN LDG LH1 SN',
                    'MAIN_LDG_RH1_SN' => 'MAIN LDG RH1 SN',
                    'MAIN_LDG_LH2_SN' => 'MAIN LDG LH2 SN',
                    'MAIN_LDG_RH2_SN' => 'MAIN LDG RH2 SN',
                    'MAIN_LDG_LH3_SN' => 'MAIN LDG LH3 SN',
                    'MAIN_LDG_RH3_SN' => 'MAIN LDG RH3 SN',
                ],
            ],
        ],
        '2' => [
            'title' => 'Airframe and APU',
            'items' => [
                'AirFrame' => [
                    'Data_Source_Airframe' => 'Data Source Airframe',
                    'Utilization_Start_date_Airframe' => 'Utilization Start Date Airframe',
                    'Utilization_End_date_Airframe' => 'Utilization End Date Airframe',
                    'Last_Utilization_date_Airframe' => 'Last Utilization Date Airframe ??',
                    'Monthly_Airframe_Utilization_FH' => 'Monthly Airframe FH Utilization',
                    'Monthly_Airframe_Utilization_FC' => 'Monthly Airframe FC Utilization',
                    'Airframe_TSN_at_Latest_Utilization_date' => 'Airframe TSN at Latest Utilization Date',
                    'Airframe_CSN_at_Latest_Utilization_date' => 'Airframe CSN at Latest Utilization Date',
                ],
                'APU' => [
                    'IS_APU_UTILIZATION_CALCULATED_FROM_AIRFRAME' => 'Is APU utilization calculated from Airframe ?',
                    'MULTIPLICATION_FACTOR_AIRFRAME_FH/APU_H' => 'Multiplication factor Airframe FH/APU H',
                    'MULTIPLICATION_FACTOR_APU_H/APU_CY' => 'Multiplication factor APU H/APU C',
                    'APU_Location' => 'APU Location',
                    'Data_Source_APU' => 'Data Source APU',
                    'Utilization_Start_date_APU' => 'Utilization Start Date APU',
                    'Utilization_End_date_APU' => 'Utilization End Date APU',
                    'Last_Utilization_date_APU' => 'Last Utilization Date APU',
                    'Monthly_APU_Utilization_APU_H' => 'Monthly APU H Utilization',
                    'Monthly_APU_Utilization_APU_C' => 'Monthly APU C Utilization',
                    'APU_TSN_at_Latest_Utilization_date' => 'APU TSN at Latest Utilization Date',
                    'APU_CSN_at_Latest_Utilization_date' => 'APU CSN at Latest Utilization Date',
                ],
            ]
        ],
        '3' => [
            'title' => 'Engine',
            'items' => [
                'Engine 1' => [
                    'engine_1_notes' => 'Engine 1 Notes',
                    'data_source_engine_1' => 'Data Source Engine 1',
                    'utilization_start_date_engine_1' => 'Utilization Start Date Engine 1',
                    'utilization_end_date_engine_1' => 'Utilization End Date Engine 1',
                    'last_utilization_date_engine_1' => 'Last Utilization Date Engine 1',
                    'engine_1_location' => 'Engine 1 Location',
                    'monthly_engine_1_utilization_fh' => 'Monthly Engine 1 Utilization FH',
                    'monthly_engine_1_utilization_fc' => 'Monthly Engine 1 Utilization FC',
                    'engine_1_tsn_at_latest_utilization_date' => 'Engine 1 TSN at Latest Utilization Date',
                    'engine_1_csn_at_latest_utilization_date' => 'Engine 1 CSN at Latest Utilization Date',
                ],
                'Engine 2' => [
                    'engine_2_notes' => 'Engine 2 Notes',
                    'data_source_engine_2' => 'Data Source Engine 2',
                    'utilization_start_date_engine_2' => 'Utilization Start Date Engine 2',
                    'utilization_end_date_engine_2' => 'Utilization End Date Engine 2',
                    'last_utilization_date_engine_2' => 'Last Utilization Date Engine 2',
                    'engine_2_location' => 'Engine 2 Location',
                    'monthly_engine_2_utilization_fh' => 'Monthly Engine 2 Utilization FH',
                    'monthly_engine_2_utilization_fc' => 'Monthly Engine 2 Utilization FC',
                    'engine_2_tsn_at_latest_utilization_date' => 'Engine 2 TSN at Latest Utilization Date',
                    'engine_2_csn_at_latest_utilization_date' => 'Engine 2 CSN at Latest Utilization Date',
                ],
                'Engine 3' => [
                    'engine_3_notes' => 'Engine 3 Notes',
                    'data_source_engine_3' => 'Data Source Engine 3',
                    'utilization_start_date_engine_3' => 'Utilization Start Date Engine 3',
                    'utilization_end_date_engine_3' => 'Utilization End Date Engine 3',
                    'last_utilization_date_engine_3' => 'Last Utilization Date Engine 3',
                    'engine_3_location' => 'Engine 3 Location',
                    'monthly_engine_3_utilization_fh' => 'Monthly Engine 3 Utilization FH',
                    'monthly_engine_3_utilization_fc' => 'Monthly Engine 3 Utilization FC',
                    'engine_3_tsn_at_latest_utilization_date' => 'Engine 3 TSN at Latest Utilization Date',
                    'engine_3_csn_at_latest_utilization_date' => 'Engine 3 CSN at Latest Utilization Date',
                ],
                'Engine 4' => [
                    'engine_4_notes' => 'Engine 4 Notes',
                    'data_source_engine_4' => 'Data Source Engine 4',
                    'utilization_start_date_engine_4' => 'Utilization Start Date Engine 4',
                    'utilization_end_date_engine_4' => 'Utilization End Date Engine 4',
                    'last_utilization_date_engine_4' => 'Last Utilization Date Engine 4',
                    'engine_4_location' => 'Engine 4 Location',
                    'monthly_engine_4_utilization_fh' => 'Monthly Engine 4 Utilization FH',
                    'monthly_engine_4_utilization_fc' => 'Monthly Engine 4 Utilization FC',
                    'engine_4_tsn_at_latest_utilization_date' => 'Engine 4 TSN at Latest Utilization Date',
                    'engine_4_csn_at_latest_utilization_date' => 'Engine 4 CSN at Latest Utilization Date',
                ],
            ]
        ],
        '4' => [
            'title' => 'Landing Gear',
            'items' => [
                'Nose LDG' => [
                    'NOSE_LDG_NOTES' => 'Nose LDG Notes',
                    'DATA_SOURCE_NOSE_LDG' => 'Data Source Nose LDG',
                    'UTILIZATION_START_DATE_NOSE_LDG' => 'Utilization Start Date Nose LDG',
                    'UTILIZATION_END_DATE_NOSE_LDG' => 'Utilization End Date Nose LDG',
                    'LAST_UTILIZATION_DATE_NOSE_LDG' => 'Last Utilization Date Nose LDG',
                    'NOSE_LDG_LOCATION' => 'Nose LDG Location',
                    'MONTHLY_NOSE_LDG_UTILIZATION_FH' => 'Monthly Nose LDG Utilization FH',
                    'MONTHLY_NOSE_LDG_UTILIZATION_FC' => 'Monthly Nose LDG Utilization FC',
                    'NOSE_LDG_TSN_AT_LATEST_UTILIZATION_DATE' => 'Nose LDG TSN at Latest Utilization Date',
                    'NOSE_LDG_CSN_AT_LATEST_UTILIZATION_DATE' => 'Nose LDG CSN at Latest Utilization Date',
                ],
                'LDG LH1' => [

                    'Main_LDG_LH1_Notes' => 'Main LDG LH 1 Notes',
                    'DATA_SOURCE_MAIN_LDG_LH1' => 'Data Source Main LDG LH 1',
                    'UTILIZATION_START_DATE_MAIN_LDG_LH1' => 'Utilization Start Date Main LDG LH 1',
                    'UTILIZATION_END_DATE_MAIN_LDG_LH1' => 'Utilization End Date Main LDG LH 1',
                    'LAST_UTILIZATION_DATE_MAIN_LDG_LH1' => 'Last Utilization Date Main LDG LH 1',
                    'MAIN_LDG_LH1_LOCATION' => 'Main LDG LH 1 Location',
                    'MONTHLY_MAIN_LDG_LH1_UTILIZATION_FH' => 'Monthly Main LDG LH 1 Utilization FH',
                    'MONTHLY_MAIN_LDG_LH1_UTILIZATION_FC' => 'Monthly Main LDG LH 1 Utilization FC',
                    'MAIN_LDG_LH1_TSN_AT_LATEST_UTILIZATION_DATE' => 'Main LDG LH 1 TSN at Latest Utilization Date',
                    'MAIN_LDG_LH1_CSN_AT_LATEST_UTILIZATION_DATE' => 'Main LDG LH 1 CSN at Latest Utilization Date',
                ],
                'LDG RH1' => [

                    'MAIN_LDG_RH1_NOTES' => 'Main LDG RH 1 Notes',
                    'DATA_SOURCE_MAIN_LDG_RH1' => 'Data Source Main LDG RH 1',
                    'UTILIZATION_START_DATE_MAIN_LDG_RH1' => 'Utilization Start Date Main LDG RH 1',
                    'UTILIZATION_END_DATE_MAIN_LDG_RH1' => 'Utilization End Date Main LDG RH 1',
                    'LAST_UTILIZATION_DATE_MAIN_LDG_RH1' => 'Last Utilization Date Main LDG RH 1',
                    'MAIN_LDG_RH1_LOCATION' => 'Main LDG RH 1 Location',
                    'MONTHLY_MAIN_LDG_RH1_UTILIZATION_FH' => 'Monthly Main LDG RH 1 Utilization FH',
                    'MONTHLY_MAIN_LDG_RH1_UTILIZATION_FC' => 'Monthly Main LDG RH 1 Utilization FC',
                    'MAIN_LDG_RH1_TSN_AT_LATEST_UTILIZATION_DATE' => 'Main LDG RH 1 TSN at Latest Utilization Date',
                    'MAIN_LDG_RH1_CSN_AT_LATEST_UTILIZATION_DATE' => 'Main LDG RH 1 CSN at Latest Utilization Date',
                ],
                'LDG LH2' => [
                    'MAIN_LDG_LH2_NOTES' => 'Main LDG LH 2 Notes',
                    'DATA_SOURCE_MAIN_LDG_LH2' => 'Data Source Main LDG LH 2',
                    'UTILIZATION_START_DATE_MAIN_LDG_LH2' => 'Utilization Start Date Main LDG LH 2',
                    'UTILIZATION_END_DATE_MAIN_LDG_LH2' => 'Utilization End Date Main LDG LH 2',
                    'LAST_UTILIZATION_DATE_MAIN_LDG_LH2' => 'Last Utilization Date Main LDG LH 2',
                    'MAIN_LDG_LH2_LOCATION' => 'Main LDG LH 2 Location',
                    'MONTHLY_MAIN_LDG_LH2_UTILIZATION_FH' => 'Monthly Main LDG LH 2 Utilization FH',
                    'MONTHLY_MAIN_LDG_LH2_UTILIZATION_FC' => 'Monthly Main LDG LH 2 Utilization FC',
                    'MAIN_LDG_LH2_TSN_AT_LATEST_UTILIZATION_DATE' => 'Main LDG LH 2 TSN at Latest Utilization Date',
                    'MAIN_LDG_LH2_CSN_AT_LATEST_UTILIZATION_DATE' => 'Main LDG LH 2 CSN at Latest Utilization Date',
                ],
                'LDG RH2' => [
                    'MAIN_LDG_RH2_NOTES' => 'Main LDG RH 2 Notes',
                    'DATA_SOURCE_MAIN_LDG_RH2' => 'Data Source Main LDG RH 2',
                    'UTILIZATION_START_DATE_MAIN_LDG_RH2' => 'Utilization Start Date Main LDG RH 2',
                    'UTILIZATION_END_DATE_MAIN_LDG_RH2' => 'Utilization End Date Main LDG RH 2',
                    'LAST_UTILIZATION_DATE_MAIN_LDG_RH2' => 'Last Utilization Date Main LDG RH 2',
                    'MAIN_LDG_RH2_LOCATION' => 'Main LDG RH 2 Location',
                    'MONTHLY_MAIN_LDG_RH2_UTILIZATION_FH' => 'Monthly Main LDG RH 2 Utilization FH',
                    'MONTHLY_MAIN_LDG_RH2_UTILIZATION_FC' => 'Monthly Main LDG RH 2 Utilization FC',
                    'MAIN_LDG_RH2_TSN_AT_LATEST_UTILIZATION_DATE' => 'Main LDG RH 2 TSN at Latest Utilization Date',
                    'MAIN_LDG_RH2_CSN_AT_LATEST_UTILIZATION_DATE' => 'Main LDG RH 2 CSN at Latest Utilization Date',
                ],
                'LDG LH3' => [
                    'MAIN_LDG_LH3_NOTES' => 'Main LDG LH 3 Notes',
                    'DATA_SOURCE_MAIN_LDG_LH3' => 'Data Source Main LDG LH 3',
                    'UTILIZATION_START_DATE_MAIN_LDG_LH3' => 'Utilization Start Date Main LDG LH 3',
                    'UTILIZATION_END_DATE_MAIN_LDG_LH3' => 'Utilization End Date Main LDG LH 3',
                    'LAST_UTILIZATION_DATE_MAIN_LDG_LH3' => 'Last Utilization Date Main LDG LH 3',
                    'MAIN_LDG_LH3_LOCATION' => 'Main LDG LH 3 Location',
                    'MONTHLY_MAIN_LDG_LH3_UTILIZATION_FH' => 'Monthly Main LDG LH 3 Utilization FH',
                    'MONTHLY_MAIN_LDG_LH3_UTILIZATION_FC' => 'Monthly Main LDG LH 3 Utilization FC',
                    'MAIN_LDG_LH3_TSN_AT_LATEST_UTILIZATION_DATE' => 'Main LDG LH 3 TSN at Latest Utilization Date',
                    'MAIN_LDG_LH3_CSN_AT_LATEST_UTILIZATION_DATE' => 'Main LDG LH 3 CSN at Latest Utilization Date',
                ],
                'LDG RH3' => [
                    'MAIN_LDG_RH3_NOTES' => 'Main LDG RH 3 Notes',
                    'DATA_SOURCE_MAIN_LDG_RH3' => 'Data Source Main LDG RH 3',
                    'UTILIZATION_START_DATE_MAIN_LDG_RH3' => 'Utilization Start Date Main LDG RH 3',
                    'UTILIZATION_END_DATE_MAIN_LDG_RH3' => 'Utilization End Date Main LDG RH 3',
                    'LAST_UTILIZATION_DATE_MAIN_LDG_RH3' => 'Last Utilization Date Main LDG RH 3',
                    'MAIN_LDG_RH3_LOCATION' => 'Main LDG RH 3 Location',
                    'MONTHLY_MAIN_LDG_RH3_UTILIZATION_FH' => 'Monthly Main LDG RH 3 Utilization FH',
                    'MONTHLY_MAIN_LDG_RH3_UTILIZATION_FC' => 'Monthly Main LDG RH 3 Utilization FC',
                    'MAIN_LDG_RH3_TSN_AT_LATEST_UTILIZATION_DATE' => 'Main LDG RH 3 TSN at Latest Utilization Date',
                    'MAIN_LDG_RH3_CSN_AT_LATEST_UTILIZATION_DATE' => 'Main LDG RH 3 CSN at Latest Utilization Date',
                ],
                'Done By' => [
                    'CreatedBy' => 'Created By',
                    'CreationDate' => 'Creation Date',
                    'ModifiedBy' => 'Modified By',
                    'ModificationDate' => 'Modification Date',
                ],
            ]
        ],
    ],
];