<?php

return [
    'Column_Names' => [
        'step1' => [
            'AIRCRAFTREGISTRATION_NUMBER' => 'Registration',
            'AIRCRAFTVARIANT_CAPTION' => 'Aircraft',
            'MODEL_CAPTION' => 'Engine',
            'Model' => 'APU',
            'MANUFACTUREDATE' => 'DOM',
            'AIRCRAFT_OWNER' => 'Aircraft Owner',
            'LEASESTART' => 'Lease Start',
            'LEASEEND' => 'Lease End',
            'ESN1_ID' => 'ESN1',
            'ESN2_ID' => 'ESN2',
            'ESN3_ID' => 'ESN3',
            'ESN4_ID' => 'ESN4',
            'APU_SN' => 'APU SN',
            'NOSE_LDG_SN' => 'NOSE LDG SN',
            'MAIN_LDG_LH1_SN' => 'MAIN LDG LH1 SN',
            'MAIN_LDG_RH1_SN' => 'MAIN LDG RH1 SN',
            'MAIN_LDG_LH2_SN' => 'MAIN LDG LH2 SN',
            'MAIN_LDG_RH2_SN' => 'MAIN LDG RH2 SN',
            'MAIN_LDG_LH3_SN' => 'MAIN LDG LH3 SN',
            'MAIN_LDG_RH3_SN' => 'MAIN LDG RH3 SN',
            'CreatedBy' => 'Created By',
            'CreationDate' => 'Creation Date',
            'ModifiedBy' => 'Modified By',
            'ModificationDate' => 'Modification Date',
        ],
        'step2' => [
            'Data_Source_Airframe' => 'Data Source Airframe',
            'ID_ABLDEALS' => 'Id Abldeals',
            'Engine_1_Location' => 'Engine 1 Location',
            'Engine_2_Location' => 'Engine 2 Location',
            'Engine_3_Location' => 'Engine 3 Location',
            'Engine_4_Location' => 'Engine 4 Location',
            'Utilization_Start_date_Airframe' => 'Utilization Start Date Airframe',
            'Utilization_End_date_Airframe' => 'Utilization End Date Airframe',
            'Last_Utilization_date_Airframe' => 'Last Utilization Date Airframe',
            'Monthly_Airframe_Utilization_FH' => 'Monthly Airframe Utilization Fh',
            'Monthly_Airframe_Utilization_FC' => 'Monthly Airframe Utilization Fc',
            'Airframe_TSN_at_Latest_Utilization_date' => 'Airframe TSN At Latest Utilization Date',
            'Airframe_CSN_at_Latest_Utilization_date' => 'Airframe CSN At Latest Utilization Date',
            'APU_Location' => 'Apu Location',
            'Data_Source_APU' => 'Data Source Apu',
            'Utilization_Start_date_APU' => 'Utilization Start Date Apu',
            'Utilization_End_date_APU' => 'Utilization End Date Apu',
            'Last_Utilization_date_APU' => 'Last Utilization Date Apu',
            'Monthly_APU_Utilization_APU_H' => 'Monthly Apu Utilization Apu H',
            'Monthly_APU_Utilization_APU_C' => 'Monthly Apu Utilization Apu C',
            'APU_TSN_at_Latest_Utilization_date' => 'Apu TSN At Latest Utilization Date',
            'APU_CSN_at_Latest_Utilization_date' => 'Apu CSN At Latest Utilization Date',
            'CreatedBy' => 'Created By',
            'CreationDate' => 'Creation Date',
            'ModifiedBy' => 'Modified By',
            'ModificationDate' => 'Modification Date',
        ],
    ]
];